name: Run Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  test-without-mbstring:
    strategy:
      fail-fast: false
      matrix:
        operating-system: [ ubuntu-latest ]
        php-version:
          - "8.4"
          - "8.3"
          - "8.2"
          - "8.1"

    name: PHP ${{ matrix.php-version }} (without mbstring)
    runs-on: ${{ matrix.operating-system }}

    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: dom, curl, libxml, xml, xmlreader, xmlwriter, zip, zlib
          tools: composer:v2

      - name: Validate composer.json and composer.lock
        run: composer validate --strict

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}-no-mbstring
          restore-keys: |
            ${{ runner.os }}-php-${{ matrix.php-version }}-no-mbstring

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Verify mbstring is disabled
        run: |
          php -m | grep -i mbstring && exit 1 || echo "mbstring is disabled as expected"

      - name: Run test without mbstring
        run: vendor/bin/phpunit

  test-with-mbstring:
    strategy:
      fail-fast: false
      matrix:
        operating-system: [ ubuntu-latest ]
        php-version:
          - "8.4"
          - "8.3"
          - "8.2"
          - "8.1"

    name: PHP ${{ matrix.php-version }} (with mbstring)
    runs-on: ${{ matrix.operating-system }}

    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: dom, curl, libxml, mbstring, xml, xmlreader, xmlwriter, zip, zlib
          tools: composer:v2

      - name: Validate composer.json and composer.lock
        run: composer validate --strict

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}-with-mbstring
          restore-keys: |
            ${{ runner.os }}-php-${{ matrix.php-version }}-with-mbstring

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Verify mbstring is enabled
        run: |
          php -m | grep -i mbstring || exit 1
          echo "mbstring is enabled as expected"

      - name: Run test with mbstring
        run: vendor/bin/phpunit
